import { Router } from 'express';
import AccountController from '../../../controllers/api/v1/MyAccount/AccountController';
import AccountsettingsController from '../../../controllers/api/v1/MyAccount/AccountsettingsController';
import OrderdetailsController from '../../../controllers/api/v1/MyAccount/OrderdetailsController';
import OrderhistoryController from '../../../controllers/api/v1/MyAccount/OrderhistoryController';
import GarageController from '../../../controllers/api/v1/MyAccount/GarageController';
import PaymentOptionController from '../../../controllers/api/v1/MyAccount/PaymentOptionController';
import AddressesController from '../../../controllers/api/v1/MyAccount/AddressesController';
import UpdatepasswordController from '../../../controllers/api/v1/MyAccount/UpdatepasswordController';
import AddaccountController from '../../../controllers/api/v1/MyAccount/AddaccountController';

const router = Router();
const accountController = new AccountController();
const garageController = new GarageController();
const paymentOptionController = new PaymentOptionController();
const orderdetailsController = new OrderdetailsController();
const orderhistoryController = new OrderhistoryController();
const accountsettingsController = new AccountsettingsController();
const addressesController = new AddressesController();
const updatePasswordController = new UpdatepasswordController();
const addAccountController = new AddaccountController();

router.get('/', accountController.index.bind(accountController));
router.get('/order-history', orderhistoryController.orders.bind(orderhistoryController));
router.get('/order-details', orderdetailsController.details.bind(orderdetailsController));
router.get('/track-order-details', orderdetailsController.trackOrder.bind(orderdetailsController));
router.get('/garage', garageController.index.bind(garageController));
router.get('/add-payment-option', paymentOptionController.add.bind(paymentOptionController));
router.get('/payment-option', paymentOptionController.index.bind(paymentOptionController));
router.get('/account-setting', accountsettingsController.index.bind(accountsettingsController));
router.get('/reset-password', accountsettingsController.reset.bind(accountsettingsController));
router.get('/track-order', accountController.trackOrder.bind(accountController));
router.get('/rma', accountController.rma.bind(accountController));
router.get('/addresses', addressesController.index.bind(addressesController));
router.get('/add-address', addressesController.add.bind(addressesController));
router.get('/edit-address', addressesController.edit.bind(addressesController));
router.post('/update-password', updatePasswordController.update.bind(updatePasswordController));
router.post('/add-account', addAccountController.add.bind(addAccountController));

export default router;
