version: '3'
services:
  app:
    image: nexus-node-composite:dev
    build:
      dockerfile: docker/app/Dockerfile.dev
      context: ./
    env_file: .env
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    ports:
      - ${APP_PORT}:3000

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
