export default {
  HOME: 'home',
  MAKE: 'make',
  SEARCH_KEYWORDS: 'search_keywords',
  SEARCH_PART: 'search_part',
  MAKE_MODEL: 'make_model',
  MAKE_MODEL_PART: 'make_model_part',
  MAKE_PART: 'make_part',
  BRAND: 'brand',
  BRAND_PART: 'brand_part',
  PART: 'part',
  YEAR_MAKE_MODEL_PART: 'year_make_model_part',
  VLP: 'vlp',
  SKU: 'sku',
  PDP: 'pdp',
  PAGE_NOT_FOUND: 'page_not_found',
  NO_MATCH: 'nomatch',
  DIRECTORY: {
    PART: 'directory_parts',
    BRAND: 'directory_brands',
    MAKE: 'directory_makes',
  },
  MYACCOUNT: {
    ORDER_HISTORY: 'myaccount_order_history',
    ORDER_DETAILS: 'myaccount_order_details',
    ADDRESSES: 'myaccount_addresses',
    NEW_ADDRESS: 'myaccount_add_address',
    EDIT_ADDRESS: 'myaccount_edit_address',
    PAYMENT_OPTIONS: 'myaccount_payment_options',
    NEW_PAYMENT_OPTIONS: 'myaccount_add_payment',
    GARAGE: 'myaccount_garage',
    LOGIN_DETAILS: 'myaccount_login_details',
    TRACK_ORDER_DETAILS: 'myaccount_track_order_details',
  },
};
