const TTL_DAY = 60 * 60 * 24;
const PRODUCT_TTL = 60 * 60 * 2.5; // 2.5 hours

export default {
  PRODUCT_OPTIONS: TTL_DAY,
  GET_PAGE_HEADER: TTL_DAY,
  GET_SEO_YEAR: TTL_DAY,
  GET_TOP_40_PARTS: TTL_DAY,
  GET_BRAND_PART: TTL_DAY,
  GET_BRAND_PART_MAKE: TTL_DAY,
  GET_SHOP_BY_PARTS: TTL_DAY,
  GET_VEHICLE_FITMENT: TTL_DAY,
  GET_SHOP_BY_MODELS: TTL_DAY,
  PRODUCT_PAGE: PRODUCT_TTL,
  PRODUCT_LISTINGS: PRODUCT_TTL,
  GET_PAGE_TYPE: 60 * 30, // 30 mins
  GET_VENDOR: TTL_DAY,
  GET_STATIC_CONTENT: TTL_DAY,
  GET_RESELLER_INFO: 60 * 60 * 5, // 5 hours
  GET_CATEGORIES: TTL_DAY,
  GET_BREADCRUMBS: TTL_DAY,
  GET_WIDGETS: TTL_DAY,
  GET_META: TTL_DAY,
  GET_YEARS: TTL_DAY,
  GET_POSTS: TTL_DAY,
  GET_TURNTO_EXPIRY: 60 * 60 * 5, // 5 hours
};
