export default {
  HOME: 'home',
  MAKE: 'make',
  SEARCH: 'search',
  CART: 'basket',
  CHECKOUT: 'checkout',
  CHECKOUT_QAS: 'qas',
  CHECKOUT_CONFIRMATION: 'confirmation',
  CHECKOUT_REVIEW: 'review',
  CHECKOUT_PAYMENT: 'payment',
  MAKE_MODEL: 'make_model',
  MAKE_MODEL_PART: 'make_model_part',
  MAKE_PART: 'make_part',
  BRAND: 'brand',
  BRAND_PART: 'brand_part',
  PART: 'part',
  YEAR_MAKE_MODEL_PART: 'year_make_model_part',
  SKU: 'sku',
  VEHICLE_LANDING_PAGE: 'vlp',
  PAGE_NOT_FOUND: 'page_not_found',
  NO_MATCH: 'nomatch',
  SAVE_QUOTE: 'save_quote',
  GET_QUOTE: 'get_quote',
  MYACCOUNT: {
    addresses: 'myaccount_addresses',
    add_address: 'myaccount_add_address',
    add_payment: 'myaccount_add_payment',
    edit_address: 'myaccount_edit_address',
    login: 'myaccount_login_register',
    main: 'myaccount_main',
    order_details: 'myaccount_order_details',
    order_history: 'myaccount_order_history',
    payment: 'myaccount_payment_options',
    rma: 'myaccount_rma',
    settings: 'myaccount_settings',
    track_order: 'myaccount_track_order',
    track_order_details: 'myaccount_track_order_details',
    vehicle: 'myaccount_garage',
    reset: 'myaccount_settings',
  },
  DIRECTORY: {
    PART: 'directory_parts',
    BRAND: 'directory_brands',
    MAKE: 'directory_makes',
  },
  STATIC_PAGES: 'home', // @Todo Change to proper meta page type
};
