export default {
  makes: 'make',
  partnames: 'part',
  brands: 'brand',
  toplevel: 'tlc',
  category: 'cat',
  makes_models: 'make_model',
  makes_partnames: 'make_part',
  brands_partnames: 'brand_part',
  makes_models_partnames: 'sku',
  years_makes_models: 'sku',
  partnames_brands_skus:'sku',
  partnames_makes_models_years: '',
  universal_partnames_brands_sku: '',
  universal_brands_partnames_sku: '',
  years_makes_models_partnames: 'part_make_model_year',
  years_makes_models_brands_partnames_sku: 'ymm_bp_sku',
  makes_models_brands_partnames_sku: 'mm_bp_sku',
  makes_models_yb_sku: 'mm_yb_sku',
  years_makes_models_sku: 'ymm_sku',
  years_makes_models_submodels_sku: 'ymms_sku',
  years_makes_models_submodels_engines_sku: 'ymmse_sku',
  years_makes_models_submodels_pla_sku: 'ymms_pla_sku',
  years_makes_models_partnames_brands: 'ymm_bp_sku',
  makes_models_brands_years_sku: 'mm_yb_sku',
  years_makes_models_partnames_brands_sku: 'ymm_sku',
  makes_models_brands_partnames_years_sku: 'ymm_sku',
  years_makes_models_submodels_partnames_brands_sku: 'ymms_sku',
  makes_models_brands_partnames_years_submodels_sku:  'ymms_sku',
  makes_models_brands_partnames_years_submodels_engines_sku: 'ymmse_sku',
  years_makes_models_submodels_engines_partnames_brands_sku: 'ymmse_sku',
};
