export default {
  make: 'make',
  part: 'part',
  brand: 'brand',
  make_model: 'make_model',
  make_part: 'make_part',
  brand_part: 'brand_part',
  make_model_part: 'make_model_part',
  year_make_model_part: 'part_make_model_year',
  nonstandard: 'nonstandard',
  category: 'category_pages',
  first_level_category: 'first_level_category',
  second_level_category: 'second_level_category',
  sku: 'sku',
  univ_sku: 'univ_sku',
  ymm_bp_sku: 'ymm_bp_sku',
  mm_bp_sku: 'mm_bp_sku',
  mm_yb_sku: 'mm_yb_sku',
  ymm_sku: 'ymm_sku',
  ymms_sku: 'ymms_sku',
  ymmse_sku: 'ymmse_sku',
  ymms_pla_sku: 'ymms_pla_sku',
  sku_pla: 'sku_pla',
  univ_sku_pla: 'univ_sku_pla',
  ymm_bp_sku_pla: 'ymm_bp_sku_pla',
  mm_bp_sku_pla: 'mm_bp_sku_pla',
  mm_yb_sku_pla: 'mm_yb_sku_pla',
  ymm_sku_pla: 'ymm_sku_pla',
  ymms_sku_pla: 'ymms_sku_pla',
  ymmse_sku_pla: 'ymmse_sku_pla',
  ymms_pla_sku_pla: 'ymms_pla_sku_pla',
  one_dimension: ['makes', 'partnames', 'brands', 'toplevel', 'category'],
  two_dimension: ['makes_models', 'makes_partnames', 'brands_partnames'],
  three_dimension: ['makes_models_partnames'],
  four_dimension: ['partnames_makes_models_years','universal_partnames_brands_sku', 'universal_brands_partnames_sku'],
  five_dimension: ['partnames_makes_models_years'],
  six_dimension: ['partnames_makes_models_years'],
  seven_dimension: ['partnames_makes_models_years'],
  eight_dimension: ['makes_models_brands_partnames_years_submodels_engines_sku', 'years_makes_models_submodels_engines_partnames_brands_sku'],
};