export default {
  make: 'make',
  part: 'part',
  brand: 'brand',
  make_model: 'make_model',
  make_part: 'make_part',
  brand_part: 'brand_part',
  make_model_part: 'make_model_part',
  year_make_model_part: 'part_make_model_year',
  nonstandard: 'nonstandard',
  category: 'category_pages',
  first_level_category: 'first_level_category',
  second_level_category: 'second_level_category',
  sku: 'sku',
  univ_sku: 'univ_sku',
  ymm_bp_sku: 'ymm_bp_sku',
  mm_bp_sku: 'mm_bp_sku',
  mm_yb_sku: 'mm_yb_sku',
  ymm_sku: 'ymm_sku',
  ymms_sku: 'ymms_sku',
  ymmse_sku: 'ymmse_sku',
  ymms_pla_sku: 'ymms_pla_sku',
  sku_pla: 'sku_pla',
  univ_sku_pla: 'univ_sku_pla',
  ymm_bp_sku_pla: 'ymm_bp_sku_pla',
  mm_bp_sku_pla: 'mm_bp_sku_pla',
  mm_yb_sku_pla: 'mm_yb_sku_pla',
  ymm_sku_pla: 'ymm_sku_pla',
  ymms_sku_pla: 'ymms_sku_pla',
  ymmse_sku_pla: 'ymmse_sku_pla',
  ymms_pla_sku_pla: 'ymms_pla_sku_pla',
  one_dimension: ['makes', 'partnames', 'brands', 'toplevel', 'category'],
  two_dimension: ['makes_models', 'makes_partnames', 'brands_partnames'],
  three_dimension: ['make_model_part'],
  four_dimension: ['part_make_model_year','univ_part_brand_sku', 'univ_brand_part_sku'],
  five_dimension: ['part_make_model_year'],
  six_dimension: ['part_make_model_year'],
  seven_dimension: ['part_make_model_year'],
  eight_dimension: ['make_model_brand_part_year_submodel_engine_sku', 'year_make_model_submodel_engine_part_brand_sku'],
};