export default {
  CATALOG_2: '/v1.0/Catalog2/',
  CATALOG: '/v5.0/Catalog/',
  SEO: '/v3.0/Seo/',
  SEO36: '/v3.6/Seo/',
  PROXY_ORDER: '/proxy-order',
  ORDER: '/Order/v1.0/index',
  ORDER_2: '/v1.1/Order2/',
  CPG: '/v1.0/Braintree/',
  CONTENT: '/v1.4/Content/',
  CONTENT_2: '/v1.0/Content2/',
  ACCOUNTS: '/MyAccount/v1.0/',
  PAGE_TYPE: '/Page/v2.0/pageType',
  PAGE_HEADER: '/Seo/v1/header/byPageType/',
  SEARCH: '/Search/v2.0/',
  DETAILS: '/Product/v1.0/',
  BREAD_CRUMBS: '/Seo/v1/breadcrumbs/byPageType/',
  METAS: '/Seo/v1/meta/byPageType/',
  SEO_CONTENTS: '/Contents/v1.0/getcontents',
  STRAPI: '/page-config-cms/chaukidar',
  MYACCOUNT_PROXY: '/proxy-myaccount/Account/v1.0/index',
  EMAIL: '/v4.0/Email/',
  EMAIL_2: '/v5.0/Email/',
  RTPI: '/PriceInventory/v1/checkInventories',
};
